version: '3'
services:
  web-app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      SPRING_FLYWAY_URL: jdbc:mysql://db:3306/gymbuddy
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gymbuddy?allowPublicKeyRetrieval=true
      AUTH0_CLIENT_ID: ZShZCT5STJSLxolYlZ6sgJiHcRXxKbLa
      AUTH0_CLIENT_SECRET: QveWVdl_fCO9PiOmYv3hJbyPaaWjqx5oe9KfB8dA5QNYo2LqW5mM90L6IJQ9sYKU
      AUTH0_AUDIANCE: https://dev-smtjhvt04ywhqy3i.us.auth0.com/api/v2/
      AUTH0_DOMAIN: https://dev-smtjhvt04ywhqy3i.us.auth0.com

  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 111
      MYSQL_DATABASE: gymbuddy
      MYSQL_USER: admin
      MYSQL_PASSOWRD: 111
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 10

  adminer:
    image: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: gymbuddy


