version: '3'
services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: gymbuddyPassword
      MYSQL_DB: gymbuddy

  mysql:
    image: mysql
    volumes:
      - /mysql-data/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: gymbuddyPassword
      MYSQL_DATABASE: gymbuddy


