server:
  port: 3000
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQLDialect
        show_sql: true
  datasource:
    url: jdbc:mysql://db:3306/gymbuddy?allowPublicKeyRetrieval=true
    username: root
    password: 111
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  flyway:
    user: root
    password: 111
    schemas: gymbuddy
    locations: classpath:db/migration
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.example.gymbuddy: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
